# Generated by Django 5.0.2 on 2024-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0049_hospitalstaffadmin_status_alter_doctor_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='is_Paid',
            field=models.BooleanField(default=False),
        ),
    ]
