# Generated by Django 5.0.3 on 2024-03-31 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0050_patientdischargedetails_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, choices=[('TPC', 'The Philippine Chemists, Inc. (TPC)'), ('UNILAB', 'United Laboratories, Inc. (UNILAB)'), ('RITEMED', 'RiteMed Philippines, Inc.')], max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('OTC', 'Over-the-counter'), ('Prescription', 'Prescription'), ('Other', 'Other')], default='Other', max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='medicine/thumbnails/')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Gastroenterologists', 'Gastroenterologists'), ('Hematologists', 'Hematologists'), ('Nephrologists', 'Nephrologists'), ('Neurologists', 'Neurologists'), ('Oncologists', 'Oncologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic Surgeons', 'Orthopedic Surgeons'), ('Pediatricians', 'Pediatricians'), ('Psychiatrists', 'Psychiatrists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists'), ('Urologists', 'Urologists'), ('Endocrinologists', 'Endocrinologists'), ('Pulmonologists', 'Pulmonologists'), ('Gynecologists', 'Gynecologists'), ('Oncology Nurses', 'Oncology Nurses'), ('General Practitioners', 'General Practitioners'), ('Dentists', 'Dentists'), ('Orthodontists', 'Orthodontists')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_num',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='License number must be 7 digits.', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('specialization', models.CharField(blank=True, choices=[('General', 'General'), ('Compounding', 'Compounding'), ('Clinical Pharmacy', 'Clinical Pharmacy'), ('Other', 'Other')], max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PharmacistProfilePic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
