# Generated by Django 5.0.3 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0052_manufacturer_alter_medicine_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='hospital.symptom'),
        ),
    ]
