# Generated by Django 5.0.3 on 2024-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_symptom_alter_medicine_dosage_medicine_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
