# Generated by Django 5.0.3 on 2024-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0054_pharmacist_first_name_pharmacist_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
