# Generated by Django 5.0.6 on 2024-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0055_pharmacist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='sale',
            field=models.BooleanField(default=True),
        ),
    ]
